site_name: Front End Transpiler Documentation
site_description: 'Documentation of the front end transpiler tool used to generate modernized React/TypeScript code from the legacy Delphi and Object Pascal Languages, in the context of the 4FOOD ERP system.'
site_author: 'Dezső-Dániel Bartha'
docs_dir: docs

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition

copyright: <h3><i>Copyright 2026 Estrategy© All Rights Reserved</i></h3>

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - json

nav:
  - Home: index.md
  - Grammar Design:
    - Introduction: gd-intro.md
    - Design Initiation: gd-init.md
    - Matching Floating-Point Numbers: gd-floats.md
    - Matching Comments and Whitespace: gd-comments-whitespace.md
    - Refining the Grammar: gd-refine.md
  - Parsing:
    - DFM Code Parsing: dfm-parsing.md
  - Steps Towards Transpiling:
    - From Parse Trees to Abstract Syntax Trees: cst-to-ast.md
plugins:
  - search
