site_name: Front End Transpiler Documentation
site_description: 'Documentation of the front end transpiler tool used to generate modernized React/TypeScript code from the legacy Delphi and Object Pascal Languages, in the context of the 4FOOD ERP system.'
site_author: 'Dezső-Dániel Bartha'
docs_dir: docs

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition

copyright: <h3><i>Copyright 2026 Estrategy© All Rights Reserved</i></h3>

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - json

nav:
  - Home: index.md
  - Grammar Design:
    - Introduction: grammar-creation/index.md
    - Design Initiation: grammar-creation/gd-init.md
    - Matching Comments and Whitespace: grammar-creation/gd-comments-whitespace.md
    - Matching Floating-Point Numbers: grammar-creation/gd-floats.md
    - Refining the Grammar: grammar-creation/gd-refine.md
  - Parsing:
    - Introduction: parsing/index.md
    - ANTLR4 Setup: parsing/antlr-setup.md
    - DFM Code Parsing: parsing/dfm-parsing.md
    - Parse Trees in ANTLR: parsing/trees.md
    - Additional Features: parsing/features.md
  - Abstract Syntax Tree Generation:
    - Parse Trees vs. Abstract Syntax Trees: ast-gen/index.md
    - Grammar Update: ast-gen/grammar-update.md
    - Parser Re-Generation and Visitor Overview: ast-gen/generation.md
    - Implementation:
      - AST Composition: ast-gen/ast-composition.md
      - Property and Component Classifications: ast-gen/node-spec.md
      - AST Builder: ast-gen/builder.md
      - Wiring Up to Main: ast-gen/wire-up.md
      - Cleanup and Generate: ast-gen/clean-and-gen.md
  - Transformation Rules:
    - Introduction: transform-rules/index.md
plugins:
  - search
